"""AgentGPTeal GCP Runtime Scaffolding Adapter.

Implements the cross-runtime bridge for Merck's AgentGPTeal framework.
Enables agents written with Merck's proprietary @entraId decorator and AWS Agent Core targets
to seamlessly deploy to Google Cloud Run and Vertex AI Agent Engine without modifying AWS code.
"""

import os
import re
import json
from pathlib import Path
from typing import Any, Dict, List, Optional


class AgentTealGcpDeployer:
    """Automates transpilation and deployment of AgentGPTeal agents to GCP Cloud Run."""

    def __init__(
        self,
        agent_file: str,
        project_id: str = "merck-clinical-mesh-prod",
        region: str = "us-central1",
        service_name: Optional[str] = None,
        entra_tenant_id: str = "merck-aad-tenant-id-882194",
        vpc_connector: str = "projects/merck-clinical-mesh-prod/locations/us-central1/connectors/conn-clinical-mesh",
    ):
        self.agent_file = Path(agent_file)
        self.project_id = project_id
        self.region = region
        self.service_name = service_name or (self.agent_file.stem.replace("_", "-") if str(agent_file) else "agent-teal-runtime")
        self.entra_tenant_id = entra_tenant_id
        self.vpc_connector = vpc_connector

    def analyze_agent(self) -> Dict[str, Any]:
        """Inspect agent source file for @entraId decorators, tools, and endpoints."""
        content = ""
        if self.agent_file.exists():
            content = self.agent_file.read_text(encoding="utf-8")

        has_entra_id = "@entraId" in content or "@entra_id" in content or "entra" in content
        tools_found = re.findall(r"@tool\s+def\s+([a-zA-Z0-9_]+)", content)
        classes_found = re.findall(r"class\s+([a-zA-Z0-9_]+)", content)

        return {
            "sourceFile": str(self.agent_file),
            "serviceName": self.service_name,
            "hasEntraIdDecorator": has_entra_id,
            "discoveredTools": tools_found,
            "discoveredClasses": classes_found,
            "runtimeTarget": "Google Cloud Run (Confidential Computing Enabled)",
            "identityFederation": f"Microsoft Entra ID Tenant {self.entra_tenant_id} -> GCP WIF ({self.project_id})",
        }

    def generate_dockerfile(self) -> str:
        """Generate hardened, GxP-compliant distroless/slim Dockerfile for Cloud Run."""
        stem = self.agent_file.stem if str(self.agent_file) else "main"
        return f"""# Generated by AgentGPTeal GCP Runtime Adapter
FROM python:3.11-slim-bookworm as builder

WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends gcc libffi-dev && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir --user -r requirements.txt

FROM python:3.11-slim-bookworm as runner
WORKDIR /app

# GxP Non-Root Security Standard (21 CFR Part 11)
RUN groupadd -g 10001 gxpuser && useradd -u 10001 -g gxpuser -s /bin/sh gxpuser
COPY --from=builder /root/.local /home/gxpuser/.local
COPY --chown=gxpuser:gxpuser . .

ENV PATH=/home/gxpuser/.local/bin:$PATH \\
    PYTHONUNBUFFERED=1 \\
    PORT=8080 \\
    APP_ENV=production \\
    MICROSOFT_ENTRA_TENANT_ID={self.entra_tenant_id}

USER 10001:10001
EXPOSE 8080

CMD ["uvicorn", "{stem}:app", "--host", "0.0.0.0", "--port", "8080", "--workers", "2"]
"""

    def generate_cloudbuild(self) -> str:
        """Generate Cloud Build pipeline to build, sign, and deploy to Cloud Run."""
        image_uri = f"{self.region}-docker.pkg.dev/{self.project_id}/a2a-agents/{self.service_name}:$COMMIT_SHA"
        return f"""# Cloud Build pipeline for AgentGPTeal agent: {self.service_name}
steps:
  # 1. Build immutable container image
  - name: 'us-docker.pkg.dev/cloud-builders/docker'
    args: ['build', '-t', '{image_uri}', '.']

  # 2. Push to Google Artifact Registry
  - name: 'us-docker.pkg.dev/cloud-builders/docker'
    args: ['push', '{image_uri}']

  # 3. Deploy to Google Cloud Run with VPC connector & Entra ID Workload Identity
  - name: 'us-docker.pkg.dev/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '{self.service_name}'
      - '--image={image_uri}'
      - '--region={self.region}'
      - '--platform=managed'
      - '--vpc-connector={self.vpc_connector}'
      - '--vpc-egress=private-ranges-only'
      - '--service-account=sa-{self.service_name}@{self.project_id}.iam.gserviceaccount.com'
      - '--no-allow-unauthenticated'

images:
  - '{image_uri}'
timeout: '600s'
"""

    def generate_service_yaml(self) -> str:
        """Generate declarative Knative Cloud Run Service YAML with Workload Identity Federation."""
        return f"""apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {self.service_name}
  namespace: '{self.project_id}'
  annotations:
    run.googleapis.com/launch-stage: GA
    run.googleapis.com/ingress: internal-and-cloud-load-balancing
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/vpc-access-connector: {self.vpc_connector}
        run.googleapis.com/vpc-access-egress: private-ranges-only
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/minScale: '1'
        autoscaling.knative.dev/maxScale: '10'
    spec:
      serviceAccountName: sa-{self.service_name}@{self.project_id}.iam.gserviceaccount.com
      containers:
      - image: {self.region}-docker.pkg.dev/{self.project_id}/a2a-agents/{self.service_name}:latest
        env:
        - name: APP_ENV
          value: "production"
        - name: EXPECTED_AUDIENCE
          value: "https://{self.service_name}-{self.region}.a.run.app"
        - name: MICROSOFT_ENTRA_TENANT_ID
          value: "{self.entra_tenant_id}"
        - name: AST_ENFORCE_RECURSION_DEPTH
          value: "64"
        resources:
          limits:
            cpu: "2000m"
            memory: "4Gi"
"""

    def generate_a2a_agent_card(self) -> Dict[str, Any]:
        """Generate A2A v1.0.0 Agent Card metadata for cross-cloud discovery."""
        return {
            "schemaVersion": "1.0.0",
            "protocolVersion": "1.0.0",
            "name": f"Merck AgentGPTeal - {self.service_name}",
            "description": "Enterprise sovereign agent running on GCP Agent Runtime with @entraId identity federation",
            "endpoint": f"https://{self.service_name}-{self.region}.a.run.app",
            "supportedInterfaces": [
                {
                    "protocolBinding": "JSON-RPC",
                    "protocolVersion": "1.0",
                    "url": f"https://{self.service_name}-{self.region}.a.run.app/a2a/v1"
                },
                {
                    "protocolBinding": "gRPC",
                    "protocolVersion": "1.0",
                    "url": f"grpcs://{self.service_name}-{self.region}.a.run.app:443"
                }
            ],
            "capabilities": {
                "gxpSanitization": True,
                "streaming": True,
                "stateTokens": True,
                "a2ui": True,
                "crossCloudDispatch": True,
                "entraIdAuth": True
            },
            "identityFederation": {
                "provider": "Microsoft Entra ID (Azure AD)",
                "tenantId": self.entra_tenant_id,
                "gcpWifPool": f"projects/{self.project_id}/locations/global/workloadIdentityPools/entra-pool",
            }
        }

    def scaffold(self, output_dir: str) -> Dict[str, str]:
        """Scaffold all deployment artifacts into output directory."""
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)

        dockerfile_path = out / "Dockerfile"
        cloudbuild_path = out / "cloudbuild.yaml"
        service_yaml_path = out / "service.yaml"
        agent_card_path = out / "agent-card.json"

        dockerfile_path.write_text(self.generate_dockerfile(), encoding="utf-8")
        cloudbuild_path.write_text(self.generate_cloudbuild(), encoding="utf-8")
        service_yaml_path.write_text(self.generate_service_yaml(), encoding="utf-8")
        agent_card_path.write_text(json.dumps(self.generate_a2a_agent_card(), indent=2), encoding="utf-8")

        return {
            "dockerfile": str(dockerfile_path),
            "cloudbuild": str(cloudbuild_path),
            "serviceYaml": str(service_yaml_path),
            "agentCard": str(agent_card_path),
            "deployCommand": f"gcloud builds submit --config={cloudbuild_path} {out}",
        }
