# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: a2a/v1/a2a.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'a2a/v1/a2a.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61\x32\x61/v1/a2a.proto\x12\x06\x61\x32\x61.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bgoogle/protobuf/empty.proto\"8\n\x1aTaskPushNotificationConfig\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\"\x94\x01\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\t\x12 \n\x05state\x18\x02 \x01(\x0e\x32\x11.a2a.v1.TaskState\x12&\n\x05input\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\'\n\x06output\x18\x04 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\r\n\x05\x65rror\x18\x05 \x01(\t\"\x8b\x01\n\x12\x45xecuteTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12+\n\nparameters\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x37\n\x0bpush_config\x18\x03 \x01(\x0b\x32\".a2a.v1.TaskPushNotificationConfig\"\xa2\x01\n\x12StreamTaskResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x12\n\nchunk_text\x18\x02 \x01(\t\x12(\n\rcurrent_state\x18\x03 \x01(\x0e\x32\x11.a2a.v1.TaskState\x12\x13\n\x0bis_terminal\x18\x04 \x01(\x08\x12(\n\x07payload\x18\x05 \x01(\x0b\x32\x17.google.protobuf.Struct\"4\n\x11\x43\x61ncelTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t*\x81\x01\n\tTaskState\x12\x1a\n\x16TASK_STATE_UNSPECIFIED\x10\x00\x12\r\n\tSUBMITTED\x10\x01\x12\x0b\n\x07WORKING\x10\x02\x12\x12\n\x0eINPUT_REQUIRED\x10\x03\x12\r\n\tCOMPLETED\x10\x04\x12\n\n\x06\x46\x41ILED\x10\x05\x12\r\n\tCANCELLED\x10\x06\x32\xce\x01\n\nA2AService\x12\x37\n\x0b\x45xecuteTask\x12\x1a.a2a.v1.ExecuteTaskRequest\x1a\x0c.a2a.v1.Task\x12\x46\n\nStreamTask\x12\x1a.a2a.v1.ExecuteTaskRequest\x1a\x1a.a2a.v1.StreamTaskResponse0\x01\x12?\n\nCancelTask\x12\x19.a2a.v1.CancelTaskRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'a2a.v1.a2a_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKSTATE']._serialized_start=658
  _globals['_TASKSTATE']._serialized_end=787
  _globals['_TASKPUSHNOTIFICATIONCONFIG']._serialized_start=87
  _globals['_TASKPUSHNOTIFICATIONCONFIG']._serialized_end=143
  _globals['_TASK']._serialized_start=146
  _globals['_TASK']._serialized_end=294
  _globals['_EXECUTETASKREQUEST']._serialized_start=297
  _globals['_EXECUTETASKREQUEST']._serialized_end=436
  _globals['_STREAMTASKRESPONSE']._serialized_start=439
  _globals['_STREAMTASKRESPONSE']._serialized_end=601
  _globals['_CANCELTASKREQUEST']._serialized_start=603
  _globals['_CANCELTASKREQUEST']._serialized_end=655
  _globals['_A2ASERVICE']._serialized_start=790
  _globals['_A2ASERVICE']._serialized_end=996
# @@protoc_insertion_point(module_scope)
