# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from a2a.v1 import a2a_pb2 as a2a_dot_v1_dot_a2a__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in a2a/v1/a2a_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class A2AServiceStub:
    """Canonical AIP-127 Compliant A2A Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteTask = channel.unary_unary(
                '/a2a.v1.A2AService/ExecuteTask',
                request_serializer=a2a_dot_v1_dot_a2a__pb2.ExecuteTaskRequest.SerializeToString,
                response_deserializer=a2a_dot_v1_dot_a2a__pb2.Task.FromString,
                _registered_method=True)
        self.StreamTask = channel.unary_stream(
                '/a2a.v1.A2AService/StreamTask',
                request_serializer=a2a_dot_v1_dot_a2a__pb2.ExecuteTaskRequest.SerializeToString,
                response_deserializer=a2a_dot_v1_dot_a2a__pb2.StreamTaskResponse.FromString,
                _registered_method=True)
        self.CancelTask = channel.unary_unary(
                '/a2a.v1.A2AService/CancelTask',
                request_serializer=a2a_dot_v1_dot_a2a__pb2.CancelTaskRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class A2AServiceServicer:
    """Canonical AIP-127 Compliant A2A Service
    """

    def ExecuteTask(self, request, context):
        """ExecuteTask: Synchronous task execution
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTask(self, request, context):
        """StreamTask: Server-streaming real-time reasoning traces & state transitions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTask(self, request, context):
        """CancelTask: Graceful cancellation of active task execution
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_A2AServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTask,
                    request_deserializer=a2a_dot_v1_dot_a2a__pb2.ExecuteTaskRequest.FromString,
                    response_serializer=a2a_dot_v1_dot_a2a__pb2.Task.SerializeToString,
            ),
            'StreamTask': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTask,
                    request_deserializer=a2a_dot_v1_dot_a2a__pb2.ExecuteTaskRequest.FromString,
                    response_serializer=a2a_dot_v1_dot_a2a__pb2.StreamTaskResponse.SerializeToString,
            ),
            'CancelTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTask,
                    request_deserializer=a2a_dot_v1_dot_a2a__pb2.CancelTaskRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'a2a.v1.A2AService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('a2a.v1.A2AService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class A2AService:
    """Canonical AIP-127 Compliant A2A Service
    """

    @staticmethod
    def ExecuteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2AService/ExecuteTask',
            a2a_dot_v1_dot_a2a__pb2.ExecuteTaskRequest.SerializeToString,
            a2a_dot_v1_dot_a2a__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/a2a.v1.A2AService/StreamTask',
            a2a_dot_v1_dot_a2a__pb2.ExecuteTaskRequest.SerializeToString,
            a2a_dot_v1_dot_a2a__pb2.StreamTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.v1.A2AService/CancelTask',
            a2a_dot_v1_dot_a2a__pb2.CancelTaskRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
